### ISSUE TITLE
Name Lookup timeout exception

### ISSUE THREAD

**Issue by EnginEken** [EnginEken/tcppinglib#1]
When unresolvable URL is sent to `resolve` or `async_resolve` functions, `resolved_ips` variable can not be set and raise an error. 

```python
>>> from tcppinglib import async_multi_tcpping
>>> import asyncio

>>> hosts = asyncio.run(async_multi_tcpping(['https://www.google.com/', 'https://www.hepsiburada.com', 'www.asdajjgjajdfaskdjfhajdjaf.com'], count=5, interval=1.5))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/engineken/Documents/projects/tcppinglib/tcppinglib/tcp_multiping.py", line 15, in async_multi_tcpping
    return [task.result() for task in tasks]
  File "/Users/engineken/Documents/projects/tcppinglib/tcppinglib/tcp_multiping.py", line 15, in <listcomp>
    return [task.result() for task in tasks]
  File "/Users/engineken/Documents/projects/tcppinglib/tcppinglib/tcp_ping.py", line 122, in async_tcpping
    return TcpHost(address, port, packets_sent, packet_lost, rtt_times, ssl_version, path_response_code, daysToExpiration, resolved_ips)
UnboundLocalError: local variable 'resolved_ips' referenced before assignment
>>> 
```

**Comment by EnginEken** [comment]
Resolved with exception handling. Edited try-except block in async_tcpping.
