### ISSUE TITLE
cannot print hosts[0] when multi_tcpping

### ISSUE THREAD

**Issue by oiramario** [EnginEken/tcppinglib#2]
>>> print(hosts)
[<Host [103.205.52.17]>, <Host [103.205.55.133]>]
>>> print(hosts[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\oiramario\AppData\Local\Programs\Python\Python39\lib\site-packages\tcppinglib\models.py", line 20, in __str__
    return f'  {self._address} - {self._resolved_ips[0]}\n' + '-' * 60 + '\n' \
IndexError: string index out of range

**Comment by EnginEken** [comment]
Hi @oiramario , this was also needed to throw PortNotOpenError since the default port is 80 and port 80 is not open for these ip addresses. I have made it to throw exception and quit. You can install the new version to resolve this and previous issue.

```python
>>> from tcppinglib import multi_tcpping
>>> hosts = multi_tcpping(['103.205.52.17', '103.205.55.133'], count=1, interval=1)
Exception type : PortNotOpenError 
Exception message : The port '80' is not open for the host '103.205.55.133'!
Exception type : PortNotOpenError 
Exception message : The port '80' is not open for the host '103.205.52.17'!
>>> 
```
