### ISSUE TITLE
exception occurred when ping https 443

### ISSUE THREAD

**Issue by oiramario** [EnginEken/tcppinglib#3]
```
>>> from tcppinglib import tcpping
>>> host = tcpping('https://www.battlenet.com.cn', count=3, interval=1)
Traceback (most recent call last):
  File "C:\Users\oiramario\AppData\Local\Programs\Python\Python39\lib\site-packages\tcppinglib\tcp_ping.py", line 180, in tcpping
    ssock = context.wrap_socket(sock, server_hostname = address)
  File "C:\Users\oiramario\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\oiramario\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\oiramario\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\oiramario\AppData\Local\Programs\Python\Python39\lib\site-packages\tcppinglib\tcp_ping.py", line 193, in tcpping
    warnings.warn(SslConnectionError(port, address))
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by oiramario** [comment]
`warnings.warn(SslConnectionError(port, address))`
change to
`warnings.warn(SslConnectionError(address))`

**Comment by oiramario** [comment]
however, how to fix 'ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]'

**Comment by EnginEken** [comment]
Hi @oiramario , thanks for reporting this issue. I have edited the warning and also made the code to continue pinging even if it throw SslConnectionError because there is other useful informations about the host.

```python
>>> from tcppinglib import tcpping
>>> host = tcpping('https://www.battlenet.com.cn', count=3, interval=1)
/Users/engineken/Documents/projects/tcppinglib/tcppinglib/tcp_ping.py:198: UserWarning: The SSL connection cannot be established for 'www.battlenet.com.cn'! But socket connection for this address can be established
  warnings.warn(SslConnectionError(address))
/Users/engineken/Documents/projects/tcppinglib/tcppinglib/tcp_ping.py:198: UserWarning: The SSL connection cannot be established for 'www.battlenet.com.cn'! But socket connection for this address can be established
  warnings.warn(SslConnectionError(address))
/Users/engineken/Documents/projects/tcppinglib/tcppinglib/tcp_ping.py:198: UserWarning: The SSL connection cannot be established for 'www.battlenet.com.cn'! But socket connection for this address can be established
  warnings.warn(SslConnectionError(address))
>>> print(host)
  www.battlenet.com.cn - 223.252.234.102
------------------------------------------------------------
  Packets sent:                    3
  Packets received:                3
  Packet lost:                     0
  Packet loss:                     0.0%
  Overall Round-trip times:        1615.216 ms / 1836.773 ms / 2276.358 ms
  DNS Round-trip times:            0.963 ms / 153.852 ms / 459.591 ms
  Connection Round-trip times:     312.208 ms / 352.922 ms / 427.395 ms
  SSL Round-trip times:            1298.528 ms / 1329.795 ms / 1388.868 ms
  Request Round-trip times:        0.0 ms / 0.0 ms / 0.0 ms
------------------------------------------------------------
>>> 
```
