### ISSUE TITLE
Functions do not read 'port' number and only try port 80.

### ISSUE THREAD

**Issue by prunckle** [EnginEken/tcppinglib#5]
I can't quite explain the behavior, but for some reason even though the default port is 443 it appears that only port 80 is being used and that any other ports (including 443) are being ignored.

I have a less than ideal environment. I'm using RHEL 8.5 as a WSL2 instance. I've created a Python 3.8 virtual environment for testing tcppinglib.

Here is the code I am testing:
```
from tcppinglib import async_multi_tcpping
import asyncio


gsni_dict = {
    'a-dictionary-of-3500-hostname-ip-k-v-pairs': '10.11.12.13',
}
gsni_ips = list(gsni_dict.values())

devices = asyncio.run(async_multi_tcpping(gsni_ips, count = 5, port = 22, timeout = 0.5, interval = 0.5, concurrent_tasks = 50))

for dev in devices:
    print(dev.is_alive, dev.avg_rtt_all)

```

And here is the output:
```
(rhel85-py38) [root@LAPTOP-IE6GQ78B python-virtual-environments]# python ../kyndryl/python/networkautomation/testing-tcpping-multiping.py
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.251.33'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.184.7'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.22.66'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.127.92'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.93.15'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.253.224'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.253.229'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.253.230'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.253.231'!
Exception type : PortNotOpenError
Exception message : The port '80' is not open for the host '10.10.253.232'!
^CTraceback (most recent call last):
  File "../kyndryl/python/networkautomation/testing-tcpping-multiping.py", line 24, in <module>
    devices = multi_tcpping(gsni_ips, count = 3, port = 22, timeout = 0.5, interval = 0.5, concurrent_tasks = 50)
  File "/mnt/c/users/scotprunckle/python-virtual-environments/rhel85-py38/lib64/python3.8/site-packages/tcppinglib/tcp_multiping.py", line 19, in multi_tcpping
    return asyncio.run(
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib64/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/mnt/c/users/scotprunckle/python-virtual-environments/rhel85-py38/lib64/python3.8/site-packages/tcppinglib/tcp_ping.py", line 53, in async_tcpping
    connection = network_sock.connect_ex((hostip, int(port)))
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished name='Task-27' coro=<async_tcpping() done, defined at /mnt/c/users/scotprunckle/python-virtual-environments/rhel85-py38/lib64/python3.8/site-packages/tcppinglib/tcp_ping.py:15> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "../kyndryl/python/networkautomation/testing-tcpping-multiping.py", line 24, in <module>
    devices = multi_tcpping(gsni_ips, count = 3, port = 22, timeout = 0.5, interval = 0.5, concurrent_tasks = 50)
  File "/mnt/c/users/scotprunckle/python-virtual-environments/rhel85-py38/lib64/python3.8/site-packages/tcppinglib/tcp_multiping.py", line 19, in multi_tcpping
    return asyncio.run(
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib64/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/mnt/c/users/scotprunckle/python-virtual-environments/rhel85-py38/lib64/python3.8/site-packages/tcppinglib/tcp_ping.py", line 53, in async_tcpping
    connection = network_sock.connect_ex((hostip, int(port)))
KeyboardInterrupt
```

I get the same port 80 issue using multi_tcpping, async_tcpping, and tcpping.

**Comment by prunckle** [comment]
I've also tested on Python 3.10.6 on WSL2 RHEL 8.5 and Win 10 Python 3.10.2 with the same result of a seemingly static port 80.

**Comment by EnginEken** [comment]
Thanks for the feedback @prunckle. I am able to undertand the reason for this problem. It is caused by the url_parse function. I am currently working on more generic and structered way of doing this. I will publish a new release and this problem will be solved.

**Comment by EnginEken** [comment]
Hi @prunckle ,

New release is published and url_parse function is removed. Also there is major changes on library. Please check the code and documentation. 

It will not be seen the port number as 80 every time now but ssl, dns and http request rtt features are removed for now. Maybe those are will be implemented in the future.
